SyliusShopBundle/views/Cart/Summary/_item.html.twig, SyliusShopBundle/views/Product/Index/_sorting.html.twig
I think we can increase the DX Font by removing old non-unused variable in twig.
Same as https://github.com/Sylius/Sylius/pull/10754
=> clean Twig unused variable

assets/js/sylius-add-to-cart.js
There was an issue, when trying to add to cart more products than it's in stock.
It wasn't able to print the right message and remove the loading class.
=> Fixed JS add to cart

SyliusShopBundle/views/Cart/Summary/_item.html.twig, SyliusShopBundle/views/Cart/Summary/_totals.html.twig, SyliusShopBundle/views/Checkout/_summary.html.twig, SyliusShopBundle/views/Common/Order/Table/_headers.html.twig, SyliusShopBundle/views/Common/Order/Table/_item.html.twig, SyliusShopBundle/views/Common/Order/Table/_shipping.html.twig, SyliusShopBundle/views/Common/Order/Table/_totals.html.twig, assets/js/fontawesome.js
=> [WIP] Sylius 1.6 update

SyliusShopBundle/views/Taxon/_horizontalMenu.html.twig, assets/scss/_custom.scss
=> fix html structure and add nested dropdown 

assets/js/sylius-variants-prices.js
If we select an option value not available for a product variant we got a JS error.
=> Fix variants prices JS error

README.md, composer.json
- Update current README with instructions
- Add version constraint in `composer.json`
Close #32
=> Prepare 0.1.1 tag

SyliusShopBundle/views/Checkout/Address/_form.html.twig
=> fix issue #28

SyliusShopBundle/views/Taxon/_horizontalMenu.html.twig, SyliusShopBundle/views/_header.html.twig, SyliusShopBundle/views/layout.html.twig
| Branch?         | 0.1
| Related tickets | fixes #10 
Same as #48
=> Issue-#10 - Fix: Collapse Javascript when the taxons is not exist

README.md, assets/js/index.js
| Related tickets | fixes #40 (duplicate of #44)
Same as #44 with updated README.
=> Remove version 4 suffix from bootstrap-native import 

SyliusShopBundle/views/Checkout/SelectShipping/_choice.html.twig
=> [fix] fix unclosed <div>

SyliusShopBundle/views/Product/Show/_addToCart.html.twig
Added a missing attribute needed for testing. See: https://github.com/Sylius/Sylius/blob/ed28c9fe5a38aab2f790813da5a7d4f039d3e58a/src/Sylius/Bundle/ShopBundle/Resources/views/Product/Show/_addToCart.html.twig#L18
=> Added missing test attribute to form element

SyliusShopBundle/views/Login/_form.html.twig
See: https://github.com/Sylius/Sylius/blob/2d39e0ced74b26bdb7514164b3662c97912a5575/src/Sylius/Bundle/ShopBundle/Resources/views/Login/_form.html.twig#L7
=> Added missing testing attributes

SyliusShopBundle/views/Common/Macro/messages.html.twig
=> Added missing testing attribute

SyliusShopBundle/views/Homepage/_latestProductsCarousel.html.twig
| Related tickets | none
Fix wrong translation key
=> Fix translation key for carousel

SyliusShopBundle/views/error.html.twig, SyliusShopBundle/views/error403.html.twig, SyliusShopBundle/views/error404.html.twig, SyliusShopBundle/views/error500.html.twig
| Related tickets | fix #52 
Update html code for error pages.
=> Update html code for error pages

SyliusShopBundle/views/Homepage/_aboutUs.html.twig, SyliusShopBundle/views/_footer.html.twig, SyliusShopBundle/views/layout.html.twig
Footer wasn't sticky, leaving white space at the bottom of pages that have little content.
=> Making footer stick to bottom of page

SyliusShopBundle/views/Checkout/Address/_addressBookSelect.html.twig
=> fix broken address book select dropdown

README.md
| Branch?         | 0.1
Update node dependencies in README.
=> Update node dependencies

README.md
| Related tickets | fixes #X, partially #Y, mentioned in #Z
Quick fix for picture in README ;)
=> Fix Sylius picture

SyliusShopBundle/views/Layout/Header/_menu.html.twig
| Bug fix?        | no
| Related tickets | fixes #87 
=> Use configured taxon for menu

SyliusShopBundle/views/Common/Macro/money.html.twig, SyliusShopBundle/views/Product/Show/_price.html.twig
=> Fix missing original price macro

composer.json
| Branch?         |  master 
| Bug fix?        | no
| Related tickets | fixes none
=> Add support for Sylius v1.11

SyliusShopBundle/views/Order/thankYou.html.twig
| Deprecations?   | no 
| Related tickets | -
=> Close h1 tag in thankyou page

README.md, SyliusShopBundle/views/Account/AddressBook/create.html.twig, SyliusShopBundle/views/Account/AddressBook/index.html.twig, SyliusShopBundle/views/Account/AddressBook/update.html.twig, SyliusShopBundle/views/Account/changePassword.html.twig, SyliusShopBundle/views/Account/profileUpdate.html.twig, SyliusShopBundle/views/Checkout/Complete/_navigation.html.twig, SyliusShopBundle/views/Common/Macro/pagination.html.twig, SyliusShopBundle/views/Grid/_default.html.twig, SyliusShopBundle/views/Homepage/_aboutUs.html.twig, SyliusShopBundle/views/Homepage/_banner.html.twig, SyliusShopBundle/views/Homepage/_list.html.twig, SyliusShopBundle/views/Homepage/_newsletter.html.twig, SyliusShopBundle/views/Homepage/_productsGrid.html.twig, SyliusShopBundle/views/Layout/Footer/Grid/_plus.html.twig, SyliusShopBundle/views/Layout/Footer/Grid/_pre_footer.html.twig, SyliusShopBundle/views/Layout/Topbar/_currencySwitcher.html.twig, SyliusShopBundle/views/Layout/Topbar/_localeSwitcher.html.twig, SyliusShopBundle/views/Layout/Topbar/_securityWidget.html.twig, SyliusShopBundle/views/Order/show.html.twig, SyliusShopBundle/views/Order/thankYou.html.twig, SyliusShopBundle/views/Product/Index/_pagination.html.twig, SyliusShopBundle/views/Product/Index/_sorting.html.twig, SyliusShopBundle/views/_footer.html.twig, SyliusShopBundle/views/layout.html.twig, SyliusShopBundle/views/register.html.twig, assets/scss/_custom.scss
| Branch?         | Sylius 1.12 or master 
| BC breaks?      | yes
| Deprecations?   | yes
Updated Bootstrap Theme to make it work with Sylius 1.12, improved UI without changing it and added missing UI elements that were added in Sylius 1.12, list of changes:
- Updated the readme file to reflect the new installation process
- Fixed bugs that appeard after moving to Sylius 1.12
- Changed deprecated code
- Fixed UI bugs: added missing spacings, improved mobile views.
- Added new UI elements that were added with Sylius 1.12
=> Sylius 1.12 Update

README.md
| Bug fix?        | no
| Deprecations?   | no 
| Related tickets | 
=> update readme for sylius 1.12

SyliusShopBundle/views/Common/Macro/pagination.html.twig
| Deprecations?   | no 
| Related tickets | 
=> fix pagination

SyliusShopBundle/views/Product/Show/_variantsPricing.html.twig, composer.json
| Deprecations?   | no 
| Related tickets | 
=> fix pricing with catalog promotion
